name:                catalog
version:             0.1.0.0
github:              "klememi/BananaStickersCatalog"
license:             MIT
author:              "Michal Klement"
maintainer:          "klememi1@fit.cvut.cz"
copyright:           "2018 Michal Klement"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/klememi1/BananaStickersCatalog#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- blaze-html
- sqlite-simple
- wai-middleware-static
- text
- base64-bytestring
- bytestring
- wai-extra
- split
- random
- wai

library:
  source-dirs: src

executables:
  catalog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catalog

tests:
  catalog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catalog
    - hspec
    - hspec-wai
    - wai
